name: Run python tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      -
        name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      -
        name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --output-format=github --select=E9,F63,F7,F82 .
          # default set of ruff rules with GitHub Annotations
          ruff check --output-format=github .
      -
        name: Run tests
        run: |
          make test
